# Generated by Django 2.2.28 on 2023-07-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230630_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cheatDays',
        ),
        migrations.RemoveField(
            model_name='user',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='user',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('cheatDays', models.SmallIntegerField(blank=True, null=True)),
                ('consumption', models.ManyToManyField(blank=True, related_name='appuser_consumption', to='home.FoodConsumption')),
            ],
        ),
    ]
